export const sportsMenu = [
  { id: 1, name: "Football", icon: "/images/icon/Icon_Football_40.svg", route: "/sports/Football", level: 1 },
  { id: 2, name: "World Cup", icon: "/static/img/wc2026.png", route: "/sports/WorldCup", level: 1, isNew: true },
  { id: 3, name: "Jackpot", icon: "/images/activity/FmjegxbnxixEBAr.svg", route: "/jackpot", level: 1, selfText: "USH6.6M" },
  { id: 4, name: "Virtuals", icon: "/images/activity/dbjzJiSbOnADjwD.svg", route: "/virtuals", level: 1 },
  { id: 5, name: "Pick12", icon: "/images/activity/VCzLgbAhETDblul.svg", route: "/pick12", level: 1 },
  { id: 6, name: "Affiliate", icon: "/images/activity/qBpECKvdiuvBmHe.svg", route: "/promotions", level: 1 },
  { id: 9, name: "Basketball", icon: "/images/icon/Icon_Basketball_40.svg", route: "/sports/Basketball", level: 1 },
  { id: 10, name: "V-Football", icon: "/images/activity/FlKJWAfxCmqdzDE.svg", route: "/virtuals", level: 1 },
  { id: 12, name: "Tennis", icon: "/images/icon/Icon_Tennis_40.svg", route: "/sports/Tennis", level: 3 },
  { id: 13, name: "Table Tennis", icon: "/images/icon/Icon_TableTennis_40.svg", route: "/sports/Table Tennis", level: 3 },
  { id: 14, name: "Ice Hockey", icon: "/images/icon/Icon_IceHockey_40.svg", route: "/sports/Ice Hockey", level: 3 },
  { id: 15, name: "Volleyball", icon: "/images/icon/Icon_Volleyball_40.svg", route: "/sports/Volleyball", level: 3 },
  { id: 16, name: "Handball", icon: "/images/icon/Icon_Handball_40.svg", route: "/sports/Handball", level: 3 },
  { id: 17, name: "Rugby", icon: "/images/icon/Icon_Rugby_40.svg", route: "/sports/Rugby", level: 3 },
  { id: 18, name: "Baseball", icon: "/images/icon/Icon_Baseball_40.svg", route: "/sports/Baseball", level: 3 },
  { id: 19, name: "Am.Football", icon: "/images/icon/Icon_AmericanFootball_40.svg", route: "/sports/American Football", level: 3 },
  { id: 20, name: "Darts", icon: "/images/icon/Icon_Darts_40.svg", route: "/sports/Darts", level: 3 },
  { id: 21, name: "Gifts", icon: "/images/icon/Icon_Gifts_40.svg", route: "/promotions", level: 2 },
  { id: 22, name: "Promotions", icon: "/images/icon/Icon_Promotions_40.svg", route: "/promotions", level: 2 },
  { id: 23, name: "FreeBet", icon: "/images/icon/Icon_FreeBets_40.svg", route: "/pick12", level: 2 },
  { id: 24, name: "Results", icon: "/images/icon/Icon_Results_40.svg", route: "/sports/results", level: 5 },
  { id: 25, name: "Prediction", icon: "/images/icon/Icon_Prediction_40.svg", route: "/pick12", level: 1 },
];

export const liveMatches = [
  {
    id: "live1",
    sport: "Football",
    league: "Uganda Premier League",
    leagueLogo: "/images/icon/Icon_Football_40.svg",
    homeTeam: "KCCA FC",
    awayTeam: "Express FC",
    homeScore: 1,
    awayScore: 0,
    minute: 63,
    isLive: true,
    markets: {
      home: 1.85,
      draw: 3.20,
      away: 4.10,
    },
  },
  {
    id: "live2",
    sport: "Football",
    league: "English Premier League",
    leagueLogo: "/images/icon/Icon_Football_40.svg",
    homeTeam: "Arsenal",
    awayTeam: "Chelsea",
    homeScore: 2,
    awayScore: 1,
    minute: 78,
    isLive: true,
    markets: {
      home: 1.45,
      draw: 4.50,
      away: 6.50,
    },
  },
  {
    id: "live3",
    sport: "Football",
    league: "Serie A",
    leagueLogo: "/images/icon/Icon_Football_40.svg",
    homeTeam: "AC Milan",
    awayTeam: "Juventus",
    homeScore: 0,
    awayScore: 0,
    minute: 34,
    isLive: true,
    markets: {
      home: 2.20,
      draw: 3.10,
      away: 3.30,
    },
  },
];

export const topMatches = [
  {
    id: "top1",
    sport: "Football",
    league: "World Cup 2026 - Group Stage",
    leagueLogo: "/images/activity/mCTDFOptZSaSNBa.png",
    homeTeam: "Brazil",
    awayTeam: "Argentina",
    startTime: "Today 21:00",
    isLive: false,
    markets: {
      home: 2.10,
      draw: 3.20,
      away: 3.50,
    },
  },
  {
    id: "top2",
    sport: "Football",
    league: "English Premier League",
    leagueLogo: "/images/icon/Icon_Football_40.svg",
    homeTeam: "Manchester City",
    awayTeam: "Liverpool",
    startTime: "Today 18:30",
    isLive: false,
    markets: {
      home: 1.90,
      draw: 3.60,
      away: 4.00,
    },
  },
  {
    id: "top3",
    sport: "Football",
    league: "La Liga",
    leagueLogo: "/images/icon/Icon_Football_40.svg",
    homeTeam: "Real Madrid",
    awayTeam: "Barcelona",
    startTime: "Tomorrow 20:00",
    isLive: false,
    markets: {
      home: 2.00,
      draw: 3.40,
      away: 3.70,
    },
  },
  {
    id: "top4",
    sport: "Football",
    league: "Champions League",
    leagueLogo: "/images/icon/Icon_Football_40.svg",
    homeTeam: "Bayern Munich",
    awayTeam: "PSG",
    startTime: "Tomorrow 21:00",
    isLive: false,
    markets: {
      home: 1.75,
      draw: 3.80,
      away: 4.60,
    },
  },
  {
    id: "top5",
    sport: "Basketball",
    league: "NBA",
    leagueLogo: "/images/icon/Icon_Basketball_40.svg",
    homeTeam: "LA Lakers",
    awayTeam: "Boston Celtics",
    startTime: "Today 02:30",
    isLive: false,
    markets: {
      home: 1.95,
      draw: null,
      away: 1.85,
    },
  },
  {
    id: "top6",
    sport: "Football",
    league: "Uganda Premier League",
    leagueLogo: "/images/icon/Icon_Football_40.svg",
    homeTeam: "Vipers SC",
    awayTeam: "SC Villa",
    startTime: "Today 16:00",
    isLive: false,
    markets: {
      home: 1.70,
      draw: 3.50,
      away: 4.80,
    },
  },
];

export const promotions = [
  {
    id: 1,
    title: "Welcome Bonus",
    description: "200% Welcome Bonus on first deposit up to USH 300,000",
    image: "/images/activity/CBpeWGUtsXzPJLy.jpg",
    tag: "NEW",
  },
  {
    id: 2,
    title: "World Cup Special",
    description: "Bet on every World Cup 2026 match and win big prizes",
    image: "/images/activity/GSQbOIkdpYrchdo.jpg",
    tag: "HOT",
  },
  {
    id: 3,
    title: "FreeBet Offer",
    description: "Get a FREE BET every week when you wager USH 5,000",
    image: "/images/activity/YwYzNXWqvuOZhVi.jpg",
    tag: "FREEBET",
  },
  {
    id: 4,
    title: "Sports Jackpot",
    description: "Predict 12 correct scores and win the jackpot of USH 6.6M",
    image: "/images/activity/ODJrAsrWagzljjh.jpg",
    tag: "JACKPOT",
  },
];

export const banners = [
  { id: 1, image: "/images/activity/CBpeWGUtsXzPJLy.jpg", link: "/promotions" },
  { id: 2, image: "/images/activity/GSQbOIkdpYrchdo.jpg", link: "/sports/WorldCup" },
  { id: 3, image: "/images/activity/YwYzNXWqvuOZhVi.jpg", link: "/promotions" },
  { id: 4, image: "/images/activity/ODJrAsrWagzljjh.jpg", link: "/jackpot" },
];
